# Generated by usvc-1.14.4
# Feel free to adjust, it will not be overridden

defmodule GrpcMock.Mixfile do
  use Mix.Project

  def project do
    [app: :grpc_mock,
     version: "0.2.0",
     elixir: "~> 1.6",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     elixirc_paths: elixirc_paths(Mix.env),
     deps: deps()]
  end

  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_), do: ["lib"]

  def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [extra_applications: [:logger],
     mod: {GrpcMock.Application, []}]
  end

  defp deps do
    [
      {:credo, "~> 0.8", only: [:dev, :test], runtime: false},
      {:grpc, "~> 0.3"},
    ]
  end
end
